<a href="https://colab.research.google.com/github/amritaa72/Runs-and-Wickets/blob/main/ball_by_ball_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [4]:
data=pd.read_csv("/content/drive/MyDrive/Cricket_pandas/virat_kohli_ball_by_ball_2022.csv")
data

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1304049,1,7,2,V Kohli,Harpreet Brar,F du Plessis,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
1,1304049,1,7,4,V Kohli,Harpreet Brar,F du Plessis,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
2,1304049,1,7,5,V Kohli,Harpreet Brar,F du Plessis,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
3,1304049,1,8,1,V Kohli,RD Chahar,F du Plessis,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
4,1304049,1,9,1,V Kohli,Harpreet Brar,F du Plessis,NaN,2,0,2,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,1312199,1,0,5,V Kohli,TA Boult,F du Plessis,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
302,1312199,1,0,6,V Kohli,TA Boult,F du Plessis,NaN,6,0,6,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
303,1312199,1,1,3,V Kohli,M Prasidh Krishna,F du Plessis,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
304,1312199,1,1,4,V Kohli,M Prasidh Krishna,F du Plessis,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
305,1312199,1,1,5,V Kohli,M Prasidh Krishna,F du Plessis,NaN,0,0,0,0,1,V Kohli,caught,SV Samson,Royal Challengers Bangalore

In [6]:
data.columns

Index(['ID', 'innings', 'overs', 'ballnumber', 'batter', 'bowler',
       'non-striker', 'extra_type', 'batsman_run', 'extras_run', 'total_run',
       'non_boundary', 'isWicketDelivery', 'player_out', 'kind',
       'fielders_involved', 'BattingTeam'],
      dtype='object')

In [7]:
data.isna()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
1,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
2,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
3,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
4,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
302,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
303,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
304,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,False
305,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [8]:
data.isna().sum()

ID                     0
innings                0
overs                  0
ballnumber             0
batter                 0
bowler                 0
non-striker            0
extra_type           292
batsman_run            0
extras_run             0
total_run              0
non_boundary           0
isWicketDelivery       0
player_out           290
kind                 290
fielders_involved    293
BattingTeam            0
dtype: int64

In [1]:
data.head()

NameError: name 'data' is not defined