<a href="https://colab.research.google.com/github/amritaa72/Runs-and-Wickets/blob/main/tips_data_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
tips_info=pd.read_csv('/content/drive/MyDrive/Cricket_pandas/tips.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
tips_info.describe()

             SINO  TotalBill       Tips       Size
count  100.000000  98.000000  94.000000  99.000000
mean    50.500000  19.805408   3.036170   2.525253
std     29.011492   7.950817   1.201806   0.824911
min      1.000000   3.070000   1.000000   1.000000
25%     25.750000  15.017500   2.035000   2.000000
50%     50.500000  18.285000   3.000000   2.000000
75%     75.250000  23.965000   3.577500   3.000000
max    100.000000  48.270000   6.730000   4.000000

In [ ]:
tips_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SINO       100 non-null    int64
 1   TotalBill  98 non-null     float64
 2   Tips       94 non-null     float64
 3   Smoker     93 non-null     object
 4   Day        93 non-null     object
 5   Time       97 non-null     object
 6   Size       99 non-null     float64
 7   Gender     93 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 6.4+ KB

In [ ]:
tips_info

    SINO  TotalBill  Tips Smoker  Day    Time  Size  Gender
0      1      16.99  1.01     No  Sun  Dinner   2.0  Female
1      2      10.34  1.66     No  Sun  Dinner   3.0    Male
2      3      21.01  3.50     No  Sun  Dinner   3.0    Male
3      4      23.68  3.31     No  Sun  Dinner   2.0    Male
4      5      24.59  3.61     No  Sun  Dinner   4.0  Female
..   ...        ...   ...    ...  ...     ...   ...     ...
95    96      40.17  4.73    Yes  Fri  Dinner   4.0    Male
96    97      27.28  4.00    Yes  Fri  Dinner   2.0    Male
97    98      12.03  1.50    Yes  Fri  Dinner   2.0    Male
98    99      21.01  3.00    Yes  Fri  Dinner   2.0    Male
99   100      25.10   NaN     No  NaN   Lunch   2.0     NaN

[100 rows x 8 columns]

In [ ]:
tips_info.loc[:,['Size']].isna()

     Size
0   False
1   False
2   False
3   False
4   False
..    ...
95  False
96  False
97  False
98  False
99  False

[100 rows x 1 columns]

In [ ]:
tips_info.columns

Index(['SINO', 'TotalBill', 'Tips', 'Smoker', 'Day', 'Time', 'Size', 'Gender'], dtype='object')